1. Process the rankings of the top five universities and create a full ranking. Universities that do not appear in the initial ranking will be processed as number 201 (for aggregation), but subsequent calculations will only be based on the Top-200

In [5]:
import numpy as np
import re
import csv
import pandas as pd
import openpyxl

# 读取数据集文件
voter = np.array(['ARWU.xlsx','QS.xlsx','THE.xlsx','UPAP.xlsx','USNEWS.xlsx'])
data = np.array(['ARWU','QS','THE','UPAP','USNEWS'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
UPAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")

str_arwu =  ','.join(ARWU['University Name'])
str_arwu = str_arwu.strip()
str_qs =  ','.join(QS['University Name'])
str_qs = str_qs.strip()
str_the =  ','.join(THE['University Name'])
str_the = str_the.strip()
str_upap =  ','.join(UPAP['University Name'])
str_upap = str_upap.strip()
str_usnews =  ','.join(USNEWS['University Name'])
str_usnews = str_usnews.strip()

for i,arwu_name in enumerate(ARWU['University Name']):
    if arwu_name not in str_usnews :
        new_university = {'University Name':arwu_name,'No':'201','Country':ARWU['Country'][i],'Group':ARWU['Group'][i]}
        USNEWS.loc[len(USNEWS)+1] = new_university
str_usnews =  ','.join(USNEWS['University Name'])
str_usnews = str_usnews.strip()

for i,upap_name in enumerate(UPAP['University Name']):
    if upap_name not in str_usnews :
        new_university = {'University Name':upap_name,'No':'201','Country':UPAP['Country'][i],'Group':UPAP['Group'][i]}
        USNEWS.loc[len(USNEWS)+1] = new_university
str_usnews =  ','.join(USNEWS['University Name'])
str_usnews = str_usnews.strip()

for i,the_name in enumerate(THE['University Name']):
    if the_name not in str_usnews :
        new_university = {'University Name':the_name,'No':'201','Country':THE['Country'][i],'Group':THE['Group'][i]}
        USNEWS.loc[len(USNEWS)+1] = new_university
str_usnews =  ','.join(USNEWS['University Name'])
str_usnews = str_usnews.strip()

for i,qs_name in enumerate(QS['University Name']):
    if qs_name not in str_usnews :
        new_university = {'University Name':qs_name,'No':'201','Country':QS['Country'][i],'Group':QS['Group'][i]}
        USNEWS.loc[len(USNEWS)+1] = new_university
str_usnews =  ','.join(USNEWS['University Name'])
str_usnews = str_usnews.strip()

# for i,usnews_name in enumerate(USNEWS['University Name']):
#     if usnews_name not in str_upap :
#         new_university = {'University Name':usnews_name,'No':'201','Country':USNEWS['Country'][i],'Group':USNEWS['Group'][i]}
#         UPAP.loc[len(UPAP)+1] = new_university

USNEWS.to_csv('USNEWS-restruct.csv',index=False)

Convert Excel to QS-restructure.xlsx university sorting, update the university sorting of the other four rankings to a unified format

In [10]:
import numpy as np
import pandas as pd

# 读取数据集文件

voter = np.array(['ARWU-restruct.xlsx','QS-restruct.xlsx','THE-restruct.xlsx','URAP-restruct.xlsx','USNEWS-restruct.xlsx'])
data = np.array(['ARWU','QS','THE','UPAP','USNEWS'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
UPAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")
# All = pd.read_excel(voter[5], sheet_name="Sheet1")

ARWU_dict = ARWU.to_dict('list')
QS_dict = QS.to_dict('list')
THE_dict = THE.to_dict('list')
UPAP_dict = UPAP.to_dict('list')
USNEWS_dict = USNEWS.to_dict('list')

update_dict = QS.to_dict('list')



def update_info(DataFrame,list):
    DataFrame_dict = DataFrame.to_dict('list')
    for i,qs_name in enumerate(DataFrame_dict.get('University Name')):
        for u,update in enumerate(list.get('University Name')):
            if update == qs_name:
                update_dict['No'][i] = list.get('No')[u]
            else:
                update_dict['No'][i] = update_dict['No'][i]


update_info(QS,USNEWS_dict)
print(update_dict.get('No'))
Update = pd.DataFrame(update_dict)
print(Update)


Update.to_csv('USNEWS-samestruct.csv',index=False)

[2, 5, 3, 8, 1, 9, 20, 26, 16, 15, 29, 33, 13, 70, 12, 32, 26, 45, 6, 16, 22, 76, 77, 19, 9, 16, 51, 56, 58, 24, 141, 4, 127, 105, 33, 130, 25, 28, 82, 14, 201, 30, 41, 201, 115, 35, 36, 21, 201, 201, 105, 74, 23, 102, 141, 38, 201, 174, 40, 119, 144, 92, 201, 46, 201, 124, 43, 192, 201, 201, 64, 201, 84, 201, 201, 52, 97, 201, 37, 201, 201, 201, 201, 72, 118, 7, 60, 95, 58, 201, 91, 201, 149, 78, 167, 135, 80, 201, 110, 161, 39, 201, 90, 151, 94, 201, 101, 31, 66, 44, 48, 201, 201, 201, 82, 70, 116, 110, 201, 114, 120, 201, 115, 80, 113, 201, 135, 95, 78, 88, 201, 135, 187, 127, 156, 201, 201, 201, 135, 67, 133, 92, 201, 201, 201, 201, 67, 201, 123, 163, 199, 166, 200, 201, 161, 103, 201, 108, 60, 201, 74, 144, 201, 201, 42, 192, 117, 201, 140, 201, 201, 124, 201, 201, 99, 201, 184, 180, 201, 62, 201, 201, 134, 201, 201, 201, 201, 55, 201, 155, 201, 201, 201, 201, 156, 185, 201, 201, 201, 183, 201, 11, 48, 89, 62, 124, 54, 73, 201, 86, 67, 119, 159, 122, 201, 180, 165, 176, 57, 141, 201, 201, 201, 107, 130, 180, 201, 99, 172, 149, 151, 201, 201, 151, 84, 201, 135, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 201, 172, 169, 201, 201, 198, 87, 103, 201, 201, 169, 192, 201, 201, 201, 163, 201, 110, 201, 201, 46, 201, 201, 201, 119, 201, 201, 201, 201, 144, 156, 199, 201, 201, 201, 188, 201, 201, 201, 147, 201, 190, 201, 201, 201, 201, 201, 195, 201, 174, 201, 201, 127, 201, 201, 201, 201, 201, 188, 201, 201, 185, 201, 176, 201, 201, 201, 109, 201, 201, 176, 201, 201, 201, 48, 52, 65, 97, 130, 148, 151, 159, 167, 169, 176, 191, 195, 197, 200]
                                       University Name   No          Country  \
0                Massachusetts Institute of Technology    2    United States
1                                 University of Oxford    5          British
2                                  Stanford University    3    United States
3                              University of Cambridge    8          British
4                                   Harvard University    1    United States
5                   California Institute of Technology    9    United States
6                              Imperial College London   20          British
7         Swiss Federal Institute of Technology Zurich   26      Switzerland
8                            University College London   16          British
9                                University of Chicago   15    United States
10                    National University of Singapore   29        Singapore
11                    Nanyang Technological University   33        Singapore
12                          University of Pennsylvania   13    United States
13   Swiss Federal Institute of Technology in Lausanne   70      Switzerland
14                                     Yale University   12    United States
15                             University of Edinburgh   32          British
16                                 Tsinghua University   26            China
17                                   Peking University   45            China
18                                 Columbia University    6    United States
19                                Princeton University   16    United States
20                                  Cornell University   22    United States
21                             University of Hong Kong   76  HongKong, China
22                                 University of Tokyo   77            Japan
23                   University of Michigan, Ann Arbor   19    United States
24                            Johns Hopkins University    9    United States
25                               University of Toronto   16           Canada
26                                   McGill University   51           Canada
27                      Australian National University   56        Australia
28                            University of Manchester   58          British
29                             Northwestern University   24    United States
..                                                 ...  ...              ...
307                             University of Aberdeen  201          British
308      Southern University of Science and Technology  201            China
309                             University of Wurzburg  185          Germany
310                               Bielefeld University  201          Germany
311                            Northeastern University  176    United States
312                             University of Canberra  201        Australia
313  Ulsan National Institute of Science and Techno...  201      South Korea
314                          University of East Anglia  201          British
315                            University of Cape Town  109     South Africa
316                           University of Notre Dame  201    United States
317                            University of Leicester  201          British
318                Queensland University of Technology  176        Australia
319                         Medical University of Graz  201          Austria
320                            University of Hohenheim  201          Germany
321                   Scuola Normale Superiore di Pisa  201            Italy
322                      Catholic University of Leuven   48          Belgium
323                    Ohio State University, Columbus   52    United States
324                                   Boston Universiy   65    United States
325   King Abdullah University of Science & Technology   97     Saudi Arabia
326       London School of Hygiene & Tropical Medicine  130          British
327               University of Massachusetts, Amherst  148    United States
328                 Oregon Health & Science University  151    United States
329          University of Chinese Academy of Sciences  159            China
330                   University Catholique of Louvain  167          Belgium
331                University of California, Riverside  169    United States
332     University of Colorado Anschutz Medical Campus  176    United States
333                           University of Cincinnati  191    United States
334                       Stony Brook University, SUNY  195    United States
335                               University of Lisbon  197         Portugal
336                        University of Witwatersrand  200     South Africa

              Group
0    North American
1          European
2    North American
3          European
4    North American
5    North American
6          European
7          European
8          European
9    North American
10     Asia/Oceania
11     Asia/Oceania
12   North American
13         European
14   North American
15         European
16     Asia/Oceania
17     Asia/Oceania
18   North American
19   North American
20   North American
21     Asia/Oceania
22     Asia/Oceania
23   North American
24   North American
25   North American
26   North American
27     Asia/Oceania
28         European
29   North American
..              ...
307        European
308    Asia/Oceania
309        European
310        European
311  North American
312    Asia/Oceania
313    Asia/Oceania
314        European
315           other
316  North American
317        European
318    Asia/Oceania
319        European
320        European
321        European
322        European
323  North American
324  North American
325    Asia/Oceania
326        European
327  North American
328  North American
329    Asia/Oceania
330        European
331  North American
332  North American
333  North American
334  North American
335        European
336           other

[337 rows x 4 columns]

Process ranking data in a unified format

In [13]:
import numpy as np
import pandas as pd

# 读取数据集文件

voter = np.array(['ARWU-samestruct.xlsx','QS-restruct.xlsx','THE-samestruct.xlsx','URAP-samestruct.xlsx','USNEWS-samestruct.xlsx'])
data = np.array(['ARWU','QS','THE','UPAP','USNEWS'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
UPAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")
# All = pd.read_excel(voter[5], sheet_name="Sheet1")

ARWU_dict = ARWU.to_dict('list')
QS_dict = QS.to_dict('list')
THE_dict = THE.to_dict('list')
UPAP_dict = UPAP.to_dict('list')
USNEWS_dict = USNEWS.to_dict('list')

update_dict = ARWU.to_dict('list')

def update_same_item_code_info(DataFrame):
    DataFrame_dict = DataFrame.to_dict('list')
    for i,dataframe_no in enumerate(DataFrame_dict.get('No')):
        update_dict['No'][i] = 202-dataframe_no


update_same_item_code_info(USNEWS)
Update = pd.DataFrame(update_dict)


Update.to_csv('Update.csv',index=False)

Convert the reconstructed file back to a fixed format and then convert the table into the format required by the RA algorithm, and submit it to the RA algorithm.

In [ ]:
import numpy as np
import pandas as pd

voter = np.array(['ARWU-samestruct.xlsx','QS-restruct.xlsx','THE-samestruct.xlsx','UPAP-samestruct.xlsx','USNEWS-samestruct.xlsx'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
UPAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")

ARWU_dict = ARWU.to_dict('list')
QS_dict = QS.to_dict('list')
THE_dict = THE.to_dict('list')
UPAP_dict = UPAP.to_dict('list')
USNEWS_dict = USNEWS.to_dict('list')

print(len(ARWU_dict.get('No')))
print(ARWU_dict.get('No'))

The ranking of the top five universities can be used to calculate their respective normalities

In [2]:
import numpy as np
import pandas as pd

voter = np.array(['ARWU-samestruct.xlsx','QS-restruct.xlsx','THE-samestruct.xlsx','URAP-samestruct.xlsx','USNEWS-samestruct.xlsx','BordaCount.xlsx','CG.xlsx','CombANZ.xlsx','CombMAX.xlsx','CombMIN.xlsx','CombMNZ.xlsx','CombSUM.xlsx','Dowdall.xlsx','ER.xlsx','HPARUNME.xlsx','iRANK.xlsx','Mean.xlsx','Medium.xlsx','PostNDCG.xlsx','RRF.xlsx'])
voter2 = np.array(['Condorcet.xlsx','Copeland.xlsx','Outranking.xlsx','MC1.xlsx','MC2.xlsx','MC3.xlsx','MC4.xlsx','MCT.xlsx','RRA.xlsx','RRA_Exact.xlsx','PrefRel.xlsx','Agglomerative.xlsx','DIBRA.xlsx'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
URAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")
BORDACOUNT = pd.read_excel(voter[5], sheet_name="Sheet1")
CG = pd.read_excel(voter[6], sheet_name="Sheet1")
COMBANZ = pd.read_excel(voter[7], sheet_name="Sheet1")
COMBMAX = pd.read_excel(voter[8], sheet_name="Sheet1")
COMBMIN = pd.read_excel(voter[9], sheet_name="Sheet1")
COMBMNZ = pd.read_excel(voter[10], sheet_name="Sheet1")
COMBSUM = pd.read_excel(voter[11], sheet_name="Sheet1")
DOWDALL = pd.read_excel(voter[12], sheet_name="Sheet1")
ER = pd.read_excel(voter[13], sheet_name="Sheet1")
HPARUNME = pd.read_excel(voter[14], sheet_name="Sheet1")
IRANK = pd.read_excel(voter[15], sheet_name="Sheet1")
MEAN = pd.read_excel(voter[16], sheet_name="Sheet1")
MEDIUM = pd.read_excel(voter[17], sheet_name="Sheet1")
POSTNDCG = pd.read_excel(voter[18], sheet_name="Sheet1")
RRF = pd.read_excel(voter[19], sheet_name="Sheet1")
Condorcet = pd.read_excel(voter2[0], sheet_name="Sheet1")
Copeland = pd.read_excel(voter2[1], sheet_name="Sheet1")
Outranking = pd.read_excel(voter2[2], sheet_name="Sheet1")
MC1 = pd.read_excel(voter2[3], sheet_name="Sheet1")
MC2 = pd.read_excel(voter2[4], sheet_name="Sheet1")
MC3 = pd.read_excel(voter2[5], sheet_name="Sheet1")
MC4 = pd.read_excel(voter2[6], sheet_name="Sheet1")
MCT = pd.read_excel(voter2[7], sheet_name="Sheet1")
RRA = pd.read_excel(voter2[8], sheet_name="Sheet1")
RRA_Exact = pd.read_excel(voter2[9], sheet_name="Sheet1")
PrefRel = pd.read_excel(voter2[10], sheet_name="Sheet1")
Agglomerative = pd.read_excel(voter2[11], sheet_name="Sheet1")
DIBRA = pd.read_excel(voter2[12], sheet_name="Sheet1")

def find_no(DataFrame,name):
    DataFrame_dict = DataFrame.to_dict('list')
    value=0
    for n,num in enumerate (DataFrame_dict.get('University Name')):
        if name == num:
            value = DataFrame_dict.get('No')[n]
        else:
            value = value
    return value

def cal_normality(DataFrame):
    sum_normality = 0
    DataFrame_dict = DataFrame.to_dict('list')
    for i in range(0,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                university_name = DataFrame_dict.get('University Name')[n]
                data = [find_no(ARWU,university_name),find_no(QS,university_name),find_no(THE,university_name),find_no(URAP,university_name),find_no(USNEWS,university_name)]
                normality = (num - np.mean(data))/np.std(data)
                sum_normality += abs(normality)
    return print(sum_normality)

cal_normality(ARWU)
cal_normality(QS)
cal_normality(THE)
cal_normality(URAP)
cal_normality(USNEWS)
print("********************************************")
cal_normality(CG)
cal_normality(COMBMIN)
cal_normality(COMBMAX)
cal_normality(COMBSUM)
cal_normality(COMBANZ)
print("*******************************************")
cal_normality(COMBMNZ)
cal_normality(POSTNDCG)
cal_normality(BORDACOUNT)
cal_normality(DOWDALL)
cal_normality(MEAN)
print("******************************************")
cal_normality(MEDIUM)
cal_normality(RRF)
cal_normality(ER)
cal_normality(HPARUNME)
cal_normality(IRANK)
print("*****************************************")
cal_normality(Condorcet)
cal_normality(Copeland)
cal_normality(Outranking)
cal_normality(MC1)
cal_normality(MC2)
print("****************************************")
cal_normality(MC3)
cal_normality(MC4)
cal_normality(MCT)
cal_normality(RRA)
cal_normality(RRA_Exact)
print("***************************************")
cal_normality(PrefRel)
cal_normality(Agglomerative)
cal_normality(DIBRA)
print("********************************************")

186.2221035598757
237.17021614560952
167.44770513520893
217.998701610831
158.4884746149956
********************************************
98.935057081864
199.65914570870427
181.71495807018496
130.5090434188993
114.30707848340032
....
114.30707848340032
145.31014739662658
126.42300724333539
78.9716585775456
103.89785501958173
....
1629.2594703491652
90.53811675228805
98.819761426976
95.73822851465734
95.16081290978978
....
380.4501205063654
380.4501205063654
398.165416950694
411.3703123240055
394.4457364072716
....
1005.5748683063468
394.4457364072716
983.4081259841763
1202.2553549138377
538.9578972158558
....
432.0909868803866
552.560931043766
391.47001237824173
....

Get Region

In [ ]:
import numpy as np
import pandas as pd

# 读取数据集文件

voter = np.array(['ARWU.xlsx','QS.xlsx','THE.xlsx','UPAP.xlsx','USNEWS.xlsx','ARWU-restruct.xlsx'])
data = np.array(['ARWU','QS','THE','UPAP','USNEWS'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
UPAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")
All = pd.read_excel(voter[5], sheet_name="Sheet1")

ARWU_dict = ARWU.to_dict('list')
QS_dict = QS.to_dict('list')
THE_dict = THE.to_dict('list')
UPAP_dict = UPAP.to_dict('list')
USNEWS_dict = USNEWS.to_dict('list')
All_dict = All.to_dict('list')


def update_group(DataFrame,list):
    DataFrame_dict = DataFrame.to_dict('list')
    DataFrame_update_dict = list
    for i in range(0,200):
        update_name = DataFrame_update_dict.get('University Name')[i]
        for n,name in enumerate(DataFrame_dict.get('University Name')):
            if update_name == name:
                DataFrame_update_dict['Group'][i] = DataFrame_dict.get('Group')[n]
            else:
                DataFrame_update_dict['Group'][i] = DataFrame_update_dict['Group'][i]
    return "Update success"


update_group(All,USNEWS_dict)
print(USNEWS_dict.get('Group'))
USNEWS1 = pd.DataFrame(USNEWS_dict)
print(USNEWS1)


USNEWS1.to_csv('USNEWS1.csv',index=False)

Similarly, calculate the impactivity of each region and divide it into four regions: North American, Europe, Asia/Oceania, and others

In [34]:
import numpy as np
import pandas as pd

voter = np.array(['ARWU-samestruct.xlsx','QS-restruct.xlsx','THE-samestruct.xlsx','URAP-samestruct.xlsx','USNEWS-samestruct.xlsx','BordaCount.xlsx','CG.xlsx','CombANZ.xlsx','CombMAX.xlsx','CombMIN.xlsx','CombMNZ.xlsx','CombSUM.xlsx','Dowdall.xlsx','ER.xlsx','HPARUNME.xlsx','iRANK.xlsx','Mean.xlsx','Medium.xlsx','PostNDCG.xlsx','RRF.xlsx'])
voter2 = np.array(['Condorcet.xlsx','Copeland.xlsx','Outranking.xlsx','MC1.xlsx','MC2.xlsx','MC3.xlsx','MC4.xlsx','MCT.xlsx','RRA.xlsx','RRA_Exact.xlsx','PrefRel.xlsx','Agglomerative.xlsx','DIBRA.xlsx'])
ARWU = pd.read_excel(voter[0], sheet_name="Sheet1")
QS = pd.read_excel(voter[1], sheet_name="Sheet1")
THE = pd.read_excel(voter[2], sheet_name="Sheet1")
URAP = pd.read_excel(voter[3], sheet_name="Sheet1")
USNEWS = pd.read_excel(voter[4], sheet_name="Sheet1")
BORDACOUNT = pd.read_excel(voter[5], sheet_name="Sheet1")
CG = pd.read_excel(voter[6], sheet_name="Sheet1")
COMBANZ = pd.read_excel(voter[7], sheet_name="Sheet1")
COMBMAX = pd.read_excel(voter[8], sheet_name="Sheet1")
COMBMIN = pd.read_excel(voter[9], sheet_name="Sheet1")
COMBMNZ = pd.read_excel(voter[10], sheet_name="Sheet1")
COMBSUM = pd.read_excel(voter[11], sheet_name="Sheet1")
DOWDALL = pd.read_excel(voter[12], sheet_name="Sheet1")
ER = pd.read_excel(voter[13], sheet_name="Sheet1")
HPARUNME = pd.read_excel(voter[14], sheet_name="Sheet1")
IRANK = pd.read_excel(voter[15], sheet_name="Sheet1")
MEAN = pd.read_excel(voter[16], sheet_name="Sheet1")
MEDIUM = pd.read_excel(voter[17], sheet_name="Sheet1")
POSTNDCG = pd.read_excel(voter[18], sheet_name="Sheet1")
RRF = pd.read_excel(voter[19], sheet_name="Sheet1")
Condorcet = pd.read_excel(voter2[0], sheet_name="Sheet1")
Copeland = pd.read_excel(voter2[1], sheet_name="Sheet1")
Outranking = pd.read_excel(voter2[2], sheet_name="Sheet1")
MC1 = pd.read_excel(voter2[3], sheet_name="Sheet1")
MC2 = pd.read_excel(voter2[4], sheet_name="Sheet1")
MC3 = pd.read_excel(voter2[5], sheet_name="Sheet1")
MC4 = pd.read_excel(voter2[6], sheet_name="Sheet1")
MCT = pd.read_excel(voter2[7], sheet_name="Sheet1")
RRA = pd.read_excel(voter2[8], sheet_name="Sheet1")
RRA_Exact = pd.read_excel(voter2[9], sheet_name="Sheet1")
PrefRel = pd.read_excel(voter2[10], sheet_name="Sheet1")
Agglomerative = pd.read_excel(voter2[11], sheet_name="Sheet1")
DIBRA = pd.read_excel(voter2[12], sheet_name="Sheet1")
def cal_na_group_q(DataFrame):
    NA_group=[]
    DataFrame_dict = DataFrame.to_dict('list')
    for i in range(1,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                group = DataFrame_dict.get('Group')[n]
                if group == "North America":
                    NA_group.append(201-i)
    return np.sum(NA_group)
def cal_eu_group_q(DataFrame):
    EU_group=[]
    DataFrame_dict = DataFrame.to_dict('list')
    for i in range(1,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                group = DataFrame_dict.get('Group')[n]
                if group == "Europe":
                    EU_group.append(201-i)
    return np.sum(EU_group)
def cal_asia_group_q(DataFrame):
    ASIA_group=[]
    DataFrame_dict = DataFrame.to_dict('list')
    for i in range(1,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                group = DataFrame_dict.get('Group')[n]
                if group == "Asia/Oceania":
                    ASIA_group.append(201-i)
    return np.sum(ASIA_group)
def cal_other_group_q(DataFrame):
    Other_group=[]
    DataFrame_dict = DataFrame.to_dict('list')
    for i in range(1,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                group = DataFrame_dict.get('Group')[n]
                if group == "other":
                    Other_group.append(201-i)
    return np.sum(Other_group)
def cal_impartiality(DataFrame):
    sum_impartiality = 0
    NA_impartiality = 0
    EU_impartiality = 0
    ASIA_impartiality = 0
    Other_impartiality = 0
    DataFrame_dict = DataFrame.to_dict('list')
    NA_group=[]
    EU_group=[]
    ASIA_group=[]
    Other_group=[]
    group=[]
    for i in range(1,200):
        for n,num in enumerate(DataFrame_dict.get('No')):
            if num == i:
                group = DataFrame_dict.get('Group')[n]
                if group == "North America":
                    NA_group.append(201-i)
                elif group == "Europe":
                    EU_group.append(201-i)
                elif group == "Asia/Oceania":
                    ASIA_group.append(201-i)
                else:
                    Other_group.append(201-i)
    data_na = [cal_na_group_q(ARWU),cal_na_group_q(QS),cal_na_group_q(THE),cal_na_group_q(URAP),cal_na_group_q(USNEWS)]
    data_eu = [cal_eu_group_q(ARWU),cal_eu_group_q(QS),cal_eu_group_q(THE),cal_eu_group_q(URAP),cal_eu_group_q(USNEWS)]
    data_asia = [cal_asia_group_q(ARWU),cal_asia_group_q(QS),cal_asia_group_q(THE),cal_asia_group_q(URAP),cal_asia_group_q(USNEWS)]
    data_other = [cal_other_group_q(ARWU),cal_other_group_q(QS),cal_other_group_q(THE),cal_other_group_q(URAP),cal_other_group_q(USNEWS)]  
    NA_impartiality = (np.sum(NA_group) - np.mean(data_na))/np.std(data_na)
    EU_impartiality = (np.sum(EU_group) - np.mean(data_eu))/np.std(data_eu)
    ASIA_impartiality = (np.sum(ASIA_group) - np.mean(data_asia))/np.std(data_asia)
    Other_impartiality = (np.sum(Other_group) - np.mean(data_other))/np.std(data_other)
    sum_impartiality = abs(NA_impartiality) + abs(EU_impartiality) + abs(ASIA_impartiality) + abs(Other_impartiality)
    print("NA_impartiality",NA_impartiality)
    print("EU_impartiality",EU_impartiality)
    print("ASIA_impartiality",ASIA_impartiality)
    print("Other_impartiality",Other_impartiality)
    return print(sum_impartiality)
cal_impartiality(DIBRA)

NA_impartiality -1.3286186317729385
EU_impartiality -0.6321361258768272
ASIA_impartiality 1.2189536102232628
Other_impartiality 1.1968153885994353
4.376523756472464